name: CI
on:
  push:
    branches:
      - 'ccr'
    paths:
      - 'App/frontend/**'
      - '.github/workflows/ci.yaml'

jobs:
  test:
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: ./App/frontend/bun.lock

      - name: Install dependencies
        working-directory: ./App/frontend
        run: bun install --frozen-lockfile

      - name: Create coverage directories
        working-directory: ./App/frontend
        run: mkdir -p coverage/{unit,e2e,merged}

      - name: Run unit tests with coverage
        working-directory: ./App/frontend
        run: |
          bun test --coverage
          if [ -f coverage/coverage-final.json ]; then
            cp coverage/coverage-final.json coverage/unit/
          fi

      - name: Run Cypress e2e tests
        working-directory: ./App/frontend
        run: |
          bun run dev &
          sleep 15
          echo "Development server should be ready..."
          bunx cypress run --config video=false || true
          if [ -f coverage/coverage-final.json ]; then
            cp coverage/coverage-final.json coverage/e2e/
          fi
          pkill -f "bun run dev" || true

      - name: Merge coverage reports
        working-directory: ./App/frontend
        run: |
          echo "Checking coverage files..."
          ls -la coverage/unit/ || true
          ls -la coverage/e2e/ || true
          
          if [ -f coverage/unit/coverage-final.json ] || [ -f coverage/e2e/coverage-final.json ]; then
            echo "Found coverage files, merging..."
            if [ -f coverage/unit/coverage-final.json ]; then
              cp coverage/unit/coverage-final.json coverage/merged/
            fi
            if [ -f coverage/e2e/coverage-final.json ]; then
              cp coverage/e2e/coverage-final.json coverage/merged/e2e-coverage.json
            fi
            node scripts/merge-coverage.js
          else
            echo "No coverage files found. Creating empty merged directory."
            touch coverage/merged/.gitkeep
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          directory: ./coverage/merged/
          flags: merged
          name: merged-coverage
          fail_ci_if_error: true
          