name: CI
on:
  push:
    branches:
      - 'ccr'
    paths:
      - 'App/frontend/**'
      - '.github/workflows/ci.yaml'

jobs:
  test:
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache-dependency-path: ./App/frontend/bun.lock

      - name: Install dependencies
        working-directory: ./App/frontend
        run: bun install --frozen-lockfile

      - name: Create coverage directories
        working-directory: ./App/frontend
        run: mkdir -p coverage/{unit,e2e,merged}

      - name: Run unit tests with coverage
        working-directory: ./App/frontend
        run: |
          echo "Running unit tests with coverage..."
          bun test --coverage
          echo "Checking for coverage files..."
          mkdir -p coverage/unit
          if [ -d .nyc_output ]; then
            cp .nyc_output/coverage-final.json coverage/unit/ || true
          fi
          nyc report --reporter=json --report-dir=coverage/unit || true

      - name: Run Cypress e2e tests
        working-directory: ./App/frontend
        run: |
          echo "Installing nyc globally..."
          npm install -g nyc
          
          echo "Starting dev server..."
          bun run dev &
          sleep 15
          echo "Development server should be ready..."
          
          echo "Running Cypress tests with coverage..."
          CYPRESS_COVERAGE=true bunx cypress run --config video=false || true
          
          echo "Generating Cypress coverage report..."
          mkdir -p coverage/e2e
          if [ -d .nyc_output ]; then
            cp .nyc_output/coverage-final.json coverage/e2e/ || true
          fi
          nyc report --reporter=json --report-dir=coverage/e2e || true
          
          echo "Stopping dev server..."
          pkill -f "bun run dev" || true

      - name: Merge coverage reports
        working-directory: ./App/frontend
        run: |
          echo "Debug: Coverage directory contents..."
          ls -la coverage/unit/ || true
          ls -la coverage/e2e/ || true
          
          mkdir -p coverage/merged
          
          if [ -f coverage/unit/coverage-final.json ]; then
            echo "Found unit test coverage"
            cp coverage/unit/coverage-final.json coverage/merged/coverage-final.json
          elif [ -f coverage/e2e/coverage-final.json ]; then
            echo "Found E2E test coverage"
            cp coverage/e2e/coverage-final.json coverage/merged/coverage-final.json
          else
            echo "No coverage files found, creating empty coverage report"
            echo '{"coverageMap":{}}' > coverage/merged/coverage-final.json
          fi
          
          # Generate HTML report
          nyc report --reporter=html --report-dir=coverage/merged/lcov-report || true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          directory: ./coverage/merged/
          flags: merged
          name: merged-coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          